package drudge.data;

import java.io.*;
import java.net.*;
import java.sql.*;

public enum UselessMessages {
NONE(0, null, "", "This is for no messages"), 
ALL(1, UselessURLException.class, "USELESSURL", "This is for all messages"),	
USELESS(2, UselessURLException.class, "USELESSURL", "This is for all uselessurls as well as all messages"),
DUPLICATE(3, DuplicateURLException.class, "DUPLICATE", "This is for all duplicate urls that are found"),
EXCLUDED(4, ExcludedURLException.class, "EXCLUDED", "This if for all excluded urls that are found"), 
NOTHTML(5, InvalidURLException.class, "INVALIDFILE", "This is for cases when a url is not a valid html file for this program to use"),
NOTOK(6, NotOKURLException.class, "NOTOKRESPONSE", "This is when the response is not and OK response"),
NOLINKS(7, NoLinksURLException.class, "NOLINKSFOUND", "This is when there are no links found on a page"),
FILETOBIG(8, FileToBigURLException.class, "FILETOBIG", "This is when a file is too big"),
NOCONTENT(9, NoContentURLException.class, "NOCONTENT", "This is when there is no content generated by the link"),
REDIRECTED(10, RedirectedURLException.class, "REDIRECTEDURL", "This is when a url request gets redirected to another url"),
BADENCODE(11, BadEncodingURLException.class, "BADENCODE", "This is when there is a bad encoding"),
NOROBOTS(12, RobotsExcludedURLException.class, "NOROBOTSALLOWED", "This is when the website doesn't allow robots"),

IO(21, IOException.class, "INPUTOUTPUT", "This indicates an IO exception has occurred"),
MALFORMED(22,  MalformedURLException.class, "MALFORMEDURL", "A malformed url was used"),
UNKNOWNHOST(23,  UnknownHostException.class, "UNKNOWNHOST", "This is when an unknown host is used"), 

EXCEPTION(31, Exception.class, "ANYEXCEPTION", "This is used for any and all exceptions!"),
NULLPOINT(32, NullPointerException.class, "NULLPOINTER", "This is used to indicate a null pointer was found."),
ILLEGALARG(33, IllegalArgumentException.class, "ILLEGALARGUMENT", "Somewhere an illegal vale was passed into a method"),

SQL(40,  SQLException.class, "SQLEXCEPTION", "This is used for all SQL exceptions!")	
	
;
/*This is for the actual class for the enum values above*/
public int num = 0;
public String mes = "";
public String hlp = "No Help at all!";
public Class<?> cls = null;

	private UselessMessages(int n) {
	num = n;
	}

	private UselessMessages(int n, Class<?> c) {
	this(n);
	cls = c;
	}

	private UselessMessages(int n, Class<?> c, String m) {
	this(n, c);
	mes = m;
	}
	
	private UselessMessages(int n, Class<?> c, String m, String h) {
	this(n, c, m);
	hlp = h;
	}

	public static UselessMessages get(int c) {
	UselessMessages useless = UselessMessages.NONE;
		for (UselessMessages u : values()) {
			if (u.num == c) {
			useless = u;
			break;
			}
		}
	return useless;
	}

	public static Class<?> getClass(int c) {
	UselessMessages u = UselessMessages.get(c);
	return u.cls;
	}

}
